-- Why a permission is not supported, alongside the three sets that say only
-- that it isn't.
--
-- ---------------------------------------------------------------------------
-- Why this is a NEW numbered file and not folded into 0001.
--
-- The project rule is "no backward-compatibility code" — no shims, no migration
-- scaffolding, change the schema directly. A reviewer reading that rule will
-- want this column moved into 0001_init.sql. It must not be, and the reason is
-- the rule's OWN stated rationale: compat code is pure cost *because there is no
-- deployed data to protect*. That premise is false here. A live development
-- database exists right now, holding real collected data (game runs and their
-- per-second buckets) with an agent actively writing to it.
--
-- store/migrate.go applies each numbered file once and records it in
-- schema_migrations. 0001 is already recorded there, so editing 0001 in place
-- would silently never run against that database: no error, no column, and the
-- permission endpoints broken until someone deleted the file and lost the data.
-- "Delete your database" is a worse outcome than the rule was written to prevent.
--
-- A numbered migration is therefore not a compatibility shim — it carries no
-- dual-read path, no deprecated field, nothing that keeps an old shape working.
-- It is schema history, which is exactly what the migrator exists to apply.
-- 0001 remains the single baseline for fresh installs and is not edited for
-- changes made after it shipped; post-baseline changes append from here onward.
-- ---------------------------------------------------------------------------
--
-- A JSON OBJECT keyed by permission ID, values stable reason codes owned by
-- whichever capability probe answered ({"game.gpu.read":"version_mismatch"}).
-- Reported whole on every Hello like perm_supported/granted/effective beside it,
-- so each report replaces this column outright; it carries no history. It only
-- ever holds ids ABSENT from perm_supported — a supported permission has nothing
-- to explain — and the registry drops any contradicting key when writing, so no
-- reader has to reconcile a row that claims both.
--
-- An absent key is NOT "no problem": it means the probe never ran, typically
-- because nothing granted the capability and an agent refuses to probe what it
-- was not granted. '{}' therefore reads as "nothing was probed", never as
-- "everything is fine", and a reader must render a missing entry as unprobed
-- rather than as an unexplained failure. The value vocabulary belongs to the
-- probes (protocol/gamesense for game capture) and is never validated here, so
-- readers must tolerate codes they do not know.

ALTER TABLE agents ADD COLUMN perm_unsupported_reasons TEXT NOT NULL DEFAULT '{}';
